version: "3"

services:
  namenode:
    image: tbytnar/portable-hadoop:hadoop-namenode
    container_name: namenode
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop-hive.env
    ports:
      - "50070:50070"
  datanode:
    image: tbytnar/portable-hadoop:hadoop-datanode
    container_name: datanode
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    ports:
      - "50075:50075"
  resourcemanager:
    image: tbytnar/portable-hadoop:hadoop-resourcemanager
    container_name: resourcemanager
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:8020 namenode:50070 datanode:50075"
    env_file:
      - ./hadoop-hive.env
    ports:
      - "8088:8088"
  historyserver:
    image: tbytnar/portable-hadoop:hadoop-historyserver
    container_name: historyserver
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:8020 namenode:50070 datanode:50075 resourcemanager:8088"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop-hive.env
    #command: ./opt/hadoop-*/sbin/mr-jobhistory-daemon.sh start historyserver
    ports:
      - "8188:8188"
      - "19888:19888"
  nodemanager:
    image: tbytnar/portable-hadoop:hadoop-nodemanager
    container_name: nodemanager
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:8020 namenode:50070 datanode:50075 resourcemanager:8088"
    env_file:
      - ./hadoop-hive.env
    ports:
      - "8042:8042"
  hive-server:
    image: tbytnar/portable-hadoop:hadoop-hiveserver
    container_name: hive-server
    env_file:
      - ./hadoop-hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083 hive-metastore:5432"
    ports:
      - "10000:10000"
    depends_on: ["namenode","datanode","hive-metastore","client","historyserver","resourcemanager","nodemanager"]
  hive-metastore:
    image: tbytnar/portable-hadoop:hive-metastore
    container_name: hive-metastore
    env_file:
      - ./hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075"
    volumes:
      - postgresql:/var/lib/postgresql/data
    ports:
      - "9083:9083"
      - "5432:5432"
    depends_on: ["namenode","datanode"]
  client:
    image: tbytnar/portable-hadoop:client
    container_name: client
    volumes:
      - client:/tmp/client
    ports: 
      - "8888:8888"
    tty: true
    env_file:
      - ./hadoop-hive.env
  spark-master:
    image: tbytnar/portable-hadoop:spark-master
    container_name: spark-master
    ports:
      - "8080:8080"
      - "8889:8888"
      - "4040:4040"
    depends_on: ["spark-worker1","spark-worker2"]
  spark-worker1:
    environment: 
      - MASTER_CONTAINER_NAME=spark-master
    image: tbytnar/portable-hadoop:spark-worker
    container_name: spark-worker1
    ports:
      - "8081:8080"
  spark-worker2:
    environment: 
      - MASTER_CONTAINER_NAME=spark-master
    image: tbytnar/portable-hadoop:spark-worker
    container_name: spark-worker2
    ports:
      - "8082:8080"
volumes:
  namenode:
  datanode:
  client:
  hadoop_historyserver:
  postgresql: